---
- name: Create MySQL database and user
  hosts: all
  become: true
  gather_facts: false

  vars:
    mysql_database: "pzproxy01"
    mysql_user: "{{ mysql_database }}"
    mysql_password: "secretsarefun"

  tasks:

    - name: Install PyMySQL
      ansible.builtin.package:
        name: python3-PyMySQL
        state: present

    - name: Create MySQL database
      community.mysql.mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock

    - name: Create MySQL user and grant all privileges
      community.mysql.mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_database }}.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
```
