---
- hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Install Docker
      ansible.builtin.package:
        name:
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'containerd.io'
          - 'docker-buildx-plugin'
          - 'docker-compose-plugin'
        state: present

    - name: Add CJ to docker Group
      user:
        name: 'cj'
        groups: docker
        append: yes
