---
- hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Add the Docker Rocky Repo
      ansible.builtin.yum_repository:
        name: docker-ce
        description: Docker CE Repo
        baseurl: https://download.docker.com/linux/rhel/docker-ce.repo
        gpgcheck: yes

    - name: Install Docker
      ansible.builtin.package:
        name:
          - 'docker-ce'
          - 'docker-ce-cli'
          - 'containerd.io'
          - 'docker-buildx-plugin'
          - 'docker-compose-plugin'
        state: present

    - name: Add CJ to docker Group
      user:
        name: 'cj'
        groups: docker
        append: yes
