---
- name: Install Security Updates
  hosts: all
  become: true
  gather_facts: true

  tasks:

  - name: Update APT package cache
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600
    when:
      - ansible_facts.os_family == "Debian"

  - name: Install security updates (APT)
    ansible.builtin.apt:
      name: "*"
      state: latest
      only_upgrade: true
      update_cache: false
    environment:
      DEBIAN_FRONTEND: noninteractive
    when:
      - ansible_facts.os_family == "Debian"

  - name: Install security updates (RPM)
    ansible.builtin.dnf:
      name: "*"
      state: latest
      security: true
      update_only: true
    when:
      - ansible.facts.os_family == "RedHat"
